   CREATE TABLE "KKR"."TABLE_DATA" 
   (    "COLUMN_INTEGER" NUMBER NOT NULL ENABLE, 
    "COLUMN_STRING" VARCHAR2(1000 BYTE), 
    "COLUMN_DOUBLE" NUMBER, 
    "COLUMN_DATE" TIMESTAMP (6), 
    "BATCH_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
     CONSTRAINT "PK_TABLE_DATA" PRIMARY KEY ("COLUMN_INTEGER")
   );