  CREATE TABLE "KKR"."TABLE_FILE" 
   (    "DATE" TIMESTAMP (6), 
    "FILE" VARCHAR2(1000 BYTE), 
    "COUNT_LINES" NUMBER, 
    "COUNT_LINES_ERROR" NUMBER, 
    "BATCH_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE
   );