COLUMN_INTEGER;COLUMN_STRING;COLUMN_DOUBLE;COLUMN_DATE
[LOOP INDEX="LINE" TYPE="COUNT" NAME="COUNT_LINES"][PARAMETER NAME="COLUMN_INTEGER" INDEXES="LINE"];[PARAMETER NAME="COLUMN_STRING" INDEXES="LINE"];[PARAMETER NAME="COLUMN_DOUBLE" INDEXES="LINE"];[PARAMETER NAME="COLUMN_DATE" INDEXES="LINE"]
[END]