COLUMN_INTEGER;COLUMN_STRING;COLUMN_DOUBLE;COLUMN_DATE
[LOOP INDEX="BLOCK" TYPE="COUNT" NAME="COUNT_BLOCKS"]# BLOCK-BEGIN: [INDEX NAME="BLOCK" FORMAT="%04d"]
[LOOP INDEX="LINE" TYPE="COUNT" NAME="COUNT_LINES"][PARAMETER NAME="COLUMN_INTEGER" INDEXES="LINE"][INDEX NAME="BLOCK" FORMAT="%04d"];[PARAMETER NAME="COLUMN_STRING" INDEXES="LINE"];[PARAMETER NAME="COLUMN_DOUBLE" INDEXES="LINE"];[PARAMETER NAME="COLUMN_DATE" INDEXES="LINE"]
[END][END]