COLUMN_INTEGER;COLUMN_INTEGER_FK;COLUMN_STRING
[LOOP INDEX="LINE" TYPE="COUNT" NAME="COUNT_LINES"][PARAMETER NAME="COLUMN_INTEGER" INDEXES="LINE"];[PARAMETER NAME="COLUMN_INTEGER_FK" INDEXES="LINE"];[PARAMETER NAME="COLUMN_STRING" INDEXES="LINE"]
[END]